### ISSUE TITLE
Only the original player can interact

### ISSUE THREAD

**Issue by Taz03** [Together-Java/TJ-Plays#6]
Right now anyone can interact with a 2048 game, make it so that only the user who started the game can interact with it.

Implementation wise, pass the id of user who started the game to button and check weather it is still the same user interacting, otherwise just ignore the interaction or send a ephemeral message saying "You can't interact with this game" or similar.

Add user id here after command name
https://github.com/Together-Java/TJ-Plays/blob/e226b5bf62b6f190f01c17490f62b91b622e1d0e/app/src/main/java/com/togetherjava/tjplays/listeners/commands/Game2048Command.java#L68-L76

check user id this method after checking command name
https://github.com/Together-Java/TJ-Plays/blob/e226b5bf62b6f190f01c17490f62b91b622e1d0e/app/src/main/java/com/togetherjava/tjplays/listeners/commands/Game2048Command.java#L44

**Comment by ooplesoft** [comment]
getUser method available from SlashCommand package.  https://ci.dv8tion.net/job/JDA/javadoc/net/dv8tion/jda/api/events/interaction/SlashCommandEvent.html

Suggestion: save Initial ID of user that creates game via slash command, then read ID of user initiating action and if they are not equal, ignore the action/ return a message.

**Comment by ooplesoft** [comment]
@Zabuzard can you assign this to me so I can try my hand at it? I think you just need to save the user ID on the initial slash command event and then do a check on the button interaction event to see if UserId is the same

**Comment by Taz03** [comment]
@ooplesoft sure, assigned u. Yes thats the correct approach

**Comment by ooplesoft** [comment]
Issue was fixed. Please reference my forked commit. Preview screenshot of message is here:
![Screenshot 2023-04-01 094544](https://user-images.githubusercontent.com/128952626/229293131-43e26b58-242b-435f-af5b-a6d954e771ab.png)

**Comment by Taz03** [comment]
@ooplesoft u will have to make a pr on this repo, which will then be reviewed and get merged

**Comment by ooplesoft** [comment]
Thanks for letting me know! This is my first time doing this :)
https://github.com/Together-Java/TJ-Plays/pull/9
