### ISSUE TITLE
Decrease font size

### ISSUE THREAD

**Issue by Taz03** [Together-Java/TJ-Plays#7]
![2023-03-01_22-46](https://user-images.githubusercontent.com/73871477/222354883-9212ff9e-5d91-41c4-806a-4cff64389007.png)
decrease font size for higher value blocks, so that it doesn't touch the sides/goes out the box

**Comment by ooplesoft** [comment]
In the Renderer file, can we do a check for values and set a font size scaler depending on orders of magnitude. So if we have 1024 go up to 16,384, we know to decrease the font size further.

**Comment by Taz03** [comment]
> In the Renderer file, can we do a check for values and set a font size scaler depending on orders of magnitude

yes thats what we want to do

> So if we have 1024 go up to 16,384

game stops after 2048

**Comment by lebedevhhh** [comment]
simple comment to assign to me this issue
